Added AWS KMS support info
cossacklabs/product-docs pull request #255
Opened 2022-07-12 14:37 UTC by ZhmakaAS

Added basic information about the new Acra-supported flags and KMS-related configuration file format. 

I think this PR should be marked as a draft until we extend all our Acra tools with supporting KMS for Acra Master Key loading as well.

2022-07-12 18:13 UTC, vixentael requested changes

2022-07-12 18:13 UTC, vixentael commented on content/acra/configuring-maintaining/general-configuration/acra-server/_index.md
> +  KMS type for using.
```suggestion
  Specify your KMS.
```

2022-07-12 18:13 UTC, vixentael commented on content/acra/configuring-maintaining/general-configuration/acra-server/_index.md
> +  Currently, supported only:
```suggestion
  Currently supported KMS types:
```

2022-07-12 18:13 UTC, vixentael commented on content/acra/configuring-maintaining/general-configuration/acra-server/_index.md
> +  KMS credentials file path in JSON format.
```suggestion
  A path to a file with KMS credentials JSON format.
```

2022-07-13 15:25 UTC, vixentael reviewed
👏

2022-07-20 14:39 UTC, vixentael approved these changes

2022-07-20 20:39 UTC, ZhmakaAS commented
Still need to add a similar section to the `log-verifier` tools when we add corresponding functionality.

2022-07-26 09:43 UTC, vixentael commented
what are we waiting here? @ZhmakaAS @Lagovas

2022-07-27 00:03 UTC, Lagovas commented
> what are we waiting here? @ZhmakaAS @Lagovas

merging https://github.com/cossacklabs/acra/pull/554. But #554 ready for merging too) If I haven't forgotten anything.

2022-07-27 08:52 UTC, vixentael commented
lets merge then 😏

2022-08-01 11:47 UTC, merged