mark secure session and connector as deprecated
cossacklabs/product-docs pull request #257
Opened 2022-07-25 23:39 UTC by Lagovas

Found that on the key management page we haven't mentioned that secure session is deprecated and several other places.
Also removed an extra paragraph about connector to simplify understanding data flow without redundant and legacy info.

2022-07-26 09:42 UTC, vixentael requested changes

2022-07-26 09:42 UTC, vixentael commented on content/acra/acra-in-depth/data-flow/_index.md
> -### Using AcraConnector and AcraServer
let's not remove the docs, because AcraConnector is deprecated but still could be used by old versions. Lets' add deprecation warnings here

2022-07-26 12:41 UTC, G1gg1L3s reviewed
There also a couple of other mentions of Secure Message:

- https://docs.cossacklabs.com/acra/getting-started/trying/#compose-files
- https://docs.cossacklabs.com/acra/guides/integrating-acra-translator-into-new-infrastructure/
- https://docs.cossacklabs.com/acra/regulations/#gdpr

I don't know whether we should mention deprecation there too, but at least we will not miss if we should.

2022-07-26 12:41 UTC, G1gg1L3s commented on content/acra/configuring-maintaining/controls-configuration-on-acratranslator/_index.md
> +  You can use either TLS (for direct connections from clients).
I think it's better to leave this line out. Or at least remove the `either` and parentheses.

2022-07-26 23:19 UTC, Lagovas commented
@G1gg1L3s 
> There also a couple of other mentions of Secure Message:
> 
> * https://docs.cossacklabs.com/acra/getting-started/trying/#compose-files
> * https://docs.cossacklabs.com/acra/guides/integrating-acra-translator-into-new-infrastructure/
> * https://docs.cossacklabs.com/acra/regulations/#gdpr
> 
> I don't know whether we should mention deprecation there too, but at least we will not miss if we should.

Yes, I saw pages with docker-compose files and tutorial for AT. They should be rewritten I think and left for future PR's. 

> I think it's better to leave this line out. Or at least remove the either and parentheses.

removed either and parentheses


@vixentael 

> let's not remove the docs, because AcraConnector is deprecated but still could be used by old versions. Lets' add deprecation warnings here

okay, returned it

2022-07-27 09:19 UTC, vixentael approved these changes

2022-07-27 09:19 UTC, vixentael commented
@ZhmakaAS @G1gg1L3s if you have any comments, or don't have any comments, let us know. otherwise, we'll merge

2022-07-27 09:44 UTC, G1gg1L3s approved these changes
Looks good!

2022-08-01 11:42 UTC, merged