Add description for TLS related flags for redis
cossacklabs/product-docs pull request #261
Opened 2022-08-25 00:52 UTC by Lagovas

Updated tools with new flags

2022-08-25 09:38 UTC, vixentael reviewed
do i understand correctly that these are the same flags, copy-pasted in 16 files?

2022-08-25 09:45 UTC, vixentael commented on content/acra/configuring-maintaining/general-configuration/acra-addzone.md
> +  Path to additional CA certificate for Redis' certificate validation (overrides `--tls_ca`).
> overrides `--tls_ca`

do we have this flag in acra-addzone?

2022-08-25 09:45 UTC, vixentael commented on content/acra/configuring-maintaining/general-configuration/acra-addzone.md
> +  "URL from configuration" above means the one configured with `--tls_crl_*_url` flags.
`--tls_crl_*_url` — where this is coming from? should we put a link here? i haven't found any `tls_crl_...` flags for acra-addzone

2022-08-26 01:02 UTC, Lagovas commented
> do i understand correctly that these are the same flags, copy-pasted in 16 files?
actually yes, but it was wrong and you catched.

> do we have this flag in acra-addzone?
no, only in acra-server/acra-translator services. so removed from all other

> --tls_crl_*_url — where this is coming from? should we put a link here? i haven't found any tls_crl_... flags for acra-addzone

same here, clarified flag that means in the note for all services except AS

2022-08-26 12:35 UTC, vixentael requested changes
Thank you! I have a small suggestion, and no further comments

2022-08-26 12:35 UTC, vixentael commented on content/acra/configuring-maintaining/general-configuration/acra-server/_index.md
> +  "URL from configuration" above means the one configured with `--tls_crl_*_url` flags.
```suggestion
  "URL from configuration" above means the one configured with `--tls_crl_*_url` flags. See [Configuring & maintaining > TLS > CRL](/acra/configuring-maintaining/tls/crl/).
```

2022-08-26 12:35 UTC, vixentael commented on content/acra/configuring-maintaining/general-configuration/acra-server/_index.md
> +  "URL from configuration" above means the one configured with `--tls_ocsp_*_url` flags.
```suggestion
  "URL from configuration" above means the one configured with `--tls_ocsp_*_url` flags, see [Configuring & maintaining > TLS > OCSP](/acra/configuring-maintaining/tls/ocsp/).
```

2022-08-28 20:09 UTC, vixentael approved these changes
Great! Please don't forget to merge into stable

2022-08-29 19:35 UTC, merged