Actualize vault TLS flags
cossacklabs/product-docs pull request #266
Opened 2022-09-09 12:39 UTC by Zhaars

Actualize Vault TLS flags according to this [PR](https://github.com/cossacklabs/acra/pull/578)

2022-09-09 14:42 UTC, vixentael requested changes
i like how clear the docs become!

pls take a look on few suggestions

2022-09-09 14:42 UTC, vixentael commented on content/acra/configuring-maintaining/general-configuration/acra-addzone.md
> +  Path to private key of the TLS certificate presented to Vault.
```suggestion
  Path to AcraServer TLS certificate's private key of the TLS certificate presented to Vault (AcraServer works as "client" when communicating with Vault).
```

yes? it's a private key from AS certificate?

2022-09-09 14:42 UTC, vixentael commented on content/acra/configuring-maintaining/general-configuration/acra-addzone.md
> +  Path to additional CA certificate for Vault certificate validation.
```suggestion
  Path to AcraServer TLS certificate's CA certificate for Vault certificate validation (AcraServer works as "client" when communicating with Vault).
```

right? here acraserver is a client

2022-09-12 15:13 UTC, Lagovas commented on content/acra/configuring-maintaining/general-configuration/acra-addzone.md
> -* `--vault_tls_ca_path=<path>`
we should leave it too due to keeping backward compatibility, as commented in related pr

2022-09-14 16:52 UTC, vixentael requested changes

2022-09-14 16:52 UTC, vixentael commented on content/acra/configuring-maintaining/general-configuration/acra-authmanager.md
> +  Path to additional CA certificate for Vault certificate validation.
@Zhaars could you please change all `--vault_tls_client*` fields with more clarifing wording, as shown on example above? As I understand, these all are the same params, they should be described similarly.

```
* `--vault_tls_client_ca=<filename>`

  Path to AcraServer TLS certificate's CA certificate for Vault certificate validation (AcraServer works as "client" when communicating with Vault).
  Empty by default.


* `--vault_tls_client_cert=<filename>`

  Path to AcraServer TLS certificate presented to Vault (AcraServer works as "client" when communicating with Vault).
  Empty by default.


* `--vault_tls_client_key=<filename>`

  Path to AcraServer TLS certificate's private key of the TLS certificate presented to Vault (AcraServer works as "client" when communicating with Vault).
  Empty by default.
```

2022-09-15 12:31 UTC, vixentael approved these changes
fantastic, thank you!

if @Lagovas doesn't have more comments, let's merge?

shall we merge it already to stable, or wait till 0.94 official release?

2022-09-15 12:38 UTC, Zhaars commented
> fantastic, thank you!
> 
> if @Lagovas doesn't have more comments, let's merge?
> 
> shall we merge it already to stable, or wait till 0.94 official release?

Sure, let's wait for @Lagovas. I think we can merge it as related changes are already in the master.

2022-09-15 12:40 UTC, Lagovas approved these changes

2022-09-15 12:44 UTC, merged