Added page about SQL prepared statements
cossacklabs/product-docs pull request #313
Opened 2023-08-10 08:01 UTC by Zhaars

2023-08-10 09:14 UTC, vixentael approved these changes

2023-08-10 09:14 UTC, vixentael commented on content/acra/security-controls/sql-prepared-statements/_index.md
> +AcraServer will detect the prepared statement query and store it destructed for further processing.
store it destructed?

2023-08-10 12:24 UTC, Lagovas requested changes

2023-08-10 12:24 UTC, Lagovas commented on content/acra/security-controls/sql-prepared-statements/_index.md
> +schemas:
let's change the order. at first show the encryptor config, after that show SET command. It is a bit easier to read and match in the mind, and logically correct. At first user should describe encryptor_config, then use this configuration in the own queries.

2023-08-10 12:24 UTC, Lagovas commented on content/acra/security-controls/sql-prepared-statements/_index.md
> + .....
let's place here the whole example schema. it hasn't much content to truncate it, but will be ready to copy/paste into own config file.

2023-08-10 12:24 UTC, Lagovas commented on content/acra/security-controls/sql-prepared-statements/_index.md
> +PREPARE stmt1 FROM 'SELECT * FROM test_table WHERE substr(searchable_field, <search HASH size>, 1) = substr(?, <search HASH size>, 1)';
```suggestion
PREPARE stmt1 FROM 'SELECT * FROM test_table WHERE substr(searchable_field, 1, <search HASH size>) = substr(?, 1, <search HASH size>)';
```

2023-08-10 12:24 UTC, Lagovas commented on content/acra/security-controls/sql-prepared-statements/_index.md
> +PREPARE stmt1 FROM 'SELECT * FROM test_table WHERE substr(searchable_field, <search HASH size>, 1) = substr(?, <search HASH size>, 1)';
looks like here we pass arguments into the substr in wrong order

2023-08-10 13:11 UTC, vixentael commented on content/acra/security-controls/sql-prepared-statements/_index.md
> +AcraServer will detect the prepared statement query and store it destructed for further processing.
+1 to @Lagovas

2023-08-15 21:04 UTC, Lagovas approved these changes

2023-08-15 21:48 UTC, vixentael commented
let's meeeerge and push to prod?

2023-09-20 17:19 UTC, merged